# Missing value + For loop

In [23]:
import pandas as pd
df=pd.read_csv("C:/Users/User/Downloads/teen_phone_addiction_dataset.csv")

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      2999 non-null   float64
 1   Name                    2999 non-null   object
 2   Age                     3000 non-null   float64
 3   Gender                  2999 non-null   object
 4   Location                2998 non-null   object
 5   School_Grade            3000 non-null   object
 6   Daily_Usage_Hours       2999 non-null   float64
 7   Sleep_Hours             3000 non-null   object
 8   Academic_Performance    3000 non-null   object
 9   Social_Interactions     3000 non-null   float64
 10  Exercise_Hours          3000 non-null   float64
 11  Anxiety_Level           2999 non-null   float64
 12  Depression_Level        2998 non-null   object
 13  Self_Esteem             2997 non-null   float64
 14  Parental_Control        2996 non-null   object
 15  Screen_Time_Before_Bed  2996 non-null   object
 16  Phone_Checks_Per_Day    2995 non-null   object
 17  Apps_Used_Daily         2995 non-null   object
 18  Time_on_Social_Media    2994 non-null   float64
 19  Time_on_Gaming          2993 non-null   float64
 20  Time_on_Education       2991 non-null   float64
 21  Phone_Usage_Purpose     2989 non-null   object
 22  Family_Communication    2989 non-null   float64
 23  Weekend_Usage_Hours     2989 non-null   float64
 24  Addiction_Level         2989 non-null   float64
dtypes: float64(13), object(12)
memory usage: 586.1+ KB

In [25]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=="object":
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_19484\4261300451.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_19484\4261300451.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      3000 non-null   float64
 1   Name                    3000 non-null   object
 2   Age                     3000 non-null   float64
 3   Gender                  3000 non-null   object
 4   Location                3000 non-null   object
 5   School_Grade            3000 non-null   object
 6   Daily_Usage_Hours       3000 non-null   float64
 7   Sleep_Hours             3000 non-null   object
 8   Academic_Performance    3000 non-null   object
 9   Social_Interactions     3000 non-null   float64
 10  Exercise_Hours          3000 non-null   float64
 11  Anxiety_Level           3000 non-null   float64
 12  Depression_Level        3000 non-null   object
 13  Self_Esteem             3000 non-null   float64
 14  Parental_Control        3000 non-null   object
 15  Screen_Time_Before_Bed  3000 non-null   object
 16  Phone_Checks_Per_Day    3000 non-null   object
 17  Apps_Used_Daily         3000 non-null   object
 18  Time_on_Social_Media    3000 non-null   float64
 19  Time_on_Gaming          3000 non-null   float64
 20  Time_on_Education       3000 non-null   float64
 21  Phone_Usage_Purpose     3000 non-null   object
 22  Family_Communication    3000 non-null   float64
 23  Weekend_Usage_Hours     3000 non-null   float64
 24  Addiction_Level         3000 non-null   float64
dtypes: float64(13), object(12)
memory usage: 586.1+ KB

# encoding + for loop

In [27]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [28]:
df.nunique()

ID                        3000
Name                      2932
Age                         11
Gender                       7
Location                  2725
School_Grade                12
Daily_Usage_Hours          109
Sleep_Hours                 77
Academic_Performance        59
Social_Interactions         15
Exercise_Hours              43
Anxiety_Level               14
Depression_Level            16
Self_Esteem                 14
Parental_Control             7
Screen_Time_Before_Bed      30
Phone_Checks_Per_Day       136
Apps_Used_Daily             19
Time_on_Social_Media        52
Time_on_Gaming              43
Time_on_Education           33
Phone_Usage_Purpose          5
Family_Communication        11
Weekend_Usage_Hours        121
Addiction_Level             81
dtype: int64

In [29]:
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=7:
            dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
            df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                3000 non-null   float64
 1   Name                              3000 non-null   int64
 2   Age                               3000 non-null   float64
 3   Location                          3000 non-null   int64
 4   School_Grade                      3000 non-null   int64
 5   Daily_Usage_Hours                 3000 non-null   float64
 6   Sleep_Hours                       3000 non-null   int64
 7   Academic_Performance              3000 non-null   int64
 8   Social_Interactions               3000 non-null   float64
 9   Exercise_Hours                    3000 non-null   float64
 10  Anxiety_Level                     3000 non-null   float64
 11  Depression_Level                  3000 non-null   int64
 12  Self_Esteem                       3000 non-null   float64
 13  Screen_Time_Before_Bed            3000 non-null   int64
 14  Phone_Checks_Per_Day              3000 non-null   int64
 15  Apps_Used_Daily                   3000 non-null   int64
 16  Time_on_Social_Media              3000 non-null   float64
 17  Time_on_Gaming                    3000 non-null   float64
 18  Time_on_Education                 3000 non-null   float64
 19  Family_Communication              3000 non-null   float64
 20  Weekend_Usage_Hours               3000 non-null   float64
 21  Addiction_Level                   3000 non-null   float64
 22  Gender_10                         3000 non-null   int64
 23  Gender_76                         3000 non-null   int64
 24  Gender_8.5                        3000 non-null   int64
 25  Gender_87                         3000 non-null   int64
 26  Gender_Female                     3000 non-null   int64
 27  Gender_Male                       3000 non-null   int64
 28  Gender_Other                      3000 non-null   int64
 29  Parental_Control_0                3000 non-null   int64
 30  Parental_Control_1                3000 non-null   int64
 31  Parental_Control_1.3              3000 non-null   int64
 32  Parental_Control_2.2              3000 non-null   int64
 33  Parental_Control_3.0              3000 non-null   int64
 34  Parental_Control_3.9              3000 non-null   int64
 35  Parental_Control_Social Media     3000 non-null   int64
 36  Phone_Usage_Purpose_Browsing      3000 non-null   int64
 37  Phone_Usage_Purpose_Education     3000 non-null   int64
 38  Phone_Usage_Purpose_Gaming        3000 non-null   int64
 39  Phone_Usage_Purpose_Other         3000 non-null   int64
 40  Phone_Usage_Purpose_Social Media  3000 non-null   int64
dtypes: float64(13), int64(28)
memory usage: 961.1 KB

# scaling

In [31]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler
standart=StandardScaler()
minmax=MinMaxScaler()
robust=RobustScaler()

In [32]:
num_col=df.select_dtypes(include=['float64','int64']).columns.tolist()

In [33]:
num_col

['ID',
 'Name',
 'Age',
 'Location',
 'School_Grade',
 'Daily_Usage_Hours',
 'Sleep_Hours',
 'Academic_Performance',
 'Social_Interactions',
 'Exercise_Hours',
 'Anxiety_Level',
 'Depression_Level',
 'Self_Esteem',
 'Screen_Time_Before_Bed',
 'Phone_Checks_Per_Day',
 'Apps_Used_Daily',
 'Time_on_Social_Media',
 'Time_on_Gaming',
 'Time_on_Education',
 'Family_Communication',
 'Weekend_Usage_Hours',
 'Addiction_Level',
 'Gender_10',
 'Gender_76',
 'Gender_8.5',
 'Gender_87',
 'Gender_Female',
 'Gender_Male',
 'Gender_Other',
 'Parental_Control_0',
 'Parental_Control_1',
 'Parental_Control_1.3',
 'Parental_Control_2.2',
 'Parental_Control_3.0',
 'Parental_Control_3.9',
 'Parental_Control_Social Media',
 'Phone_Usage_Purpose_Browsing',
 'Phone_Usage_Purpose_Education',
 'Phone_Usage_Purpose_Gaming',
 'Phone_Usage_Purpose_Other',
 'Phone_Usage_Purpose_Social Media']

# StandardScaler

In [34]:
df[num_col]=standart.fit_transform(df[num_col])

In [35]:
df.head()

,ID,Name,Age,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,Exercise_Hours,...,Parental_Control_1.3,Parental_Control_2.2,Parental_Control_3.0,Parental_Control_3.9,Parental_Control_Social Media,Phone_Usage_Purpose_Browsing,Phone_Usage_Purpose_Education,Phone_Usage_Purpose_Gaming,Phone_Usage_Purpose_Other,Phone_Usage_Purpose_Social Media
0,-1.732596,1.296377,-1.411444,-0.874555,1.244324,-0.519222,-0.158860,0.268358,-0.033849,-0.573126,...,-0.01826,-0.025828,-0.01826,-0.01826,-0.01826,1.926026,-0.498958,-0.484322,-0.510915,-0.486419
1,-1.731441,1.270302,0.488702,1.339845,0.687413,0.245235,0.097366,-0.251884,-0.033849,-0.631692,...,-0.01826,-0.025828,-0.01826,-0.01826,-0.01826,1.926026,-0.498958,-0.484322,-0.510915,-0.486419
2,-1.730286,-1.700983,-1.411444,-0.292221,-0.983318,0.398126,-0.607256,1.308841,0.754548,-0.163165,...,-0.01826,-0.025828,-0.01826,-0.01826,-0.01826,-0.519204,2.004176,-0.484322,-0.510915,-0.486419
3,-1.729131,-1.262461,0.963738,1.453502,-0.704863,-0.977896,-1.696218,0.268358,0.754548,0.305363,...,-0.01826,-0.025828,-0.01826,-0.01826,-0.01826,-0.519204,-0.498958,-0.484322,-0.510915,2.055841
4,-1.727976,1.422007,-0.936407,0.702599,1.244324,-1.283679,0.225479,-1.227337,-0.296647,0.012533,...,-0.01826,-0.025828,-0.01826,-0.01826,-0.01826,-0.519204,-0.498958,2.064742,-0.510915,-0.486419

# Minmax

In [36]:
df[num_col]=minmax.fit_transform(df[num_col])

In [37]:
df.head(2)

,ID,Name,Age,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,Exercise_Hours,...,Parental_Control_1.3,Parental_Control_2.2,Parental_Control_3.0,Parental_Control_3.9,Parental_Control_Social Media,Phone_Usage_Purpose_Browsing,Phone_Usage_Purpose_Education,Phone_Usage_Purpose_Gaming,Phone_Usage_Purpose_Other,Phone_Usage_Purpose_Social Media
0,0.000000,0.872740,0.136364,0.248899,1.000000,0.347826,0.473684,0.603448,0.04065,0.001205,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.000333,0.865234,0.227273,0.885463,0.818182,0.478261,0.526316,0.465517,0.04065,0.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

# Robust

In [38]:
df[num_col]=robust.fit_transform(df[num_col])

In [39]:
df.head()

,ID,Name,Age,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,Exercise_Hours,...,Parental_Control_1.3,Parental_Control_2.2,Parental_Control_3.0,Parental_Control_3.9,Parental_Control_Social Media,Phone_Usage_Purpose_Browsing,Phone_Usage_Purpose_Education,Phone_Usage_Purpose_Gaming,Phone_Usage_Purpose_Other,Phone_Usage_Purpose_Social Media
0,-1.000977,0.753688,-0.75,-0.504242,0.285714,-0.370370,-0.142857,0.153846,0.000000,-0.9,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,-1.000310,0.738593,0.25,0.774991,0.000000,0.185185,0.047619,-0.153846,0.000000,-1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,-0.999642,-0.981475,-0.75,-0.167835,-0.857143,0.296296,-0.476190,0.769231,0.500000,-0.2,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,-0.998975,-0.727616,0.50,0.840649,-0.714286,-0.703704,-1.285714,0.153846,0.500000,0.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,-0.998308,0.826415,-0.50,0.406861,0.285714,-0.925926,0.142857,-0.730769,-0.166667,0.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [40]:
df.tail(3)

,ID,Name,Age,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,Exercise_Hours,...,Parental_Control_1.3,Parental_Control_2.2,Parental_Control_3.0,Parental_Control_3.9,Parental_Control_Social Media,Phone_Usage_Purpose_Browsing,Phone_Usage_Purpose_Education,Phone_Usage_Purpose_Gaming,Phone_Usage_Purpose_Other,Phone_Usage_Purpose_Social Media
2997,0.999023,0.513551,-0.50,0.483585,0.000000,-0.666667,0.047619,0.961538,-0.666667,-1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2998,0.999690,-0.805146,0.25,0.473995,0.285714,0.629630,0.523810,-0.269231,-0.333333,-0.8,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2999,1.000358,-0.586278,0.25,-0.335301,-1.000000,-0.555556,0.238095,0.192308,-0.166667,1.1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0